export default [
  {
    name: { en: 'message.publish', zh: '消息发布' },
    value: 'message.publish',
    description: '',
    test_field: ['payload', 'clientid', 'username', 'topic', 'qos'],
    ctx: {
      payload: { msg: 'hello' },
      clientid: 'c_emqx',
      event: 'message.publish',
      id: '588D045CCB2C7B44B000004D10001',
      peername: '127.0.0.1:58138',
      qos: 0,
      timestamp: 1557802989171,
      topic: 't/a',
      username: 'u_emqx',
      retain: 0,
    },
    sql: 'SELECT * FROM "message.publish" WHERE topic =~ \'t/#\'',
  },
  {
    name: { en: 'message.acked', zh: '消息确认' },
    value: 'message.acked',
    description: '',
    test_field: ['payload', 'clientid', 'username', 'topic', 'qos'],
    ctx: {
      payload: { msg: 'hello' },
      clientid: 'c_emqx',
      event: 'message.acked',
      id: '588D3DD4C6820B44B0000055C0001',
      peername: '127.0.0.1:63412',
      qos: 1,
      timestamp: 1557818415802,
      topic: 't/a',
      username: 'u_emqx',
      retain: 0,
    },
    sql: 'SELECT * FROM "message.acked" WHERE topic =~ \'t/#\'',
  },
  {
    name: { en: 'message.deliver', zh: '消息投递' },
    value: 'message.deliver',
    description: '',
    test_field: ['payload', 'clientid', 'username', 'topic', 'qos'],
    ctx: {
      payload: { msg: 'hello' },
      auth_result: 'success',
      clientid: 'c_emqx',
      event: 'message.deliver',
      id: '588D3DD4C6820B44B0000055C0001',
      peername: '127.0.0.1:63412',
      qos: 1,
      timestamp: 1557818415802,
      topic: 't/a',
      username: 'u_emqx',
      zone: 'external',
      retain: 0,
    },
    sql: 'SELECT * FROM "message.deliver" WHERE topic =~ \'t/#\'',
  },
  {
    name: { en: 'message.dropped', zh: '消息丢弃' },
    value: 'message.dropped',
    description: '',
    test_field: ['payload', 'clientid', 'username', 'topic', 'qos'],
    ctx: {
      payload: { msg: 'hello' },
      clientid: 'c_emqx',
      event: 'message.dropped',
      id: '588D3DD4F8874B44B0000055C0002',
      node: 'nonode@nohost',
      peername: '127.0.0.1:63412',
      qos: 1,
      timestamp: 1557818416007,
      topic: 't/a',
      username: 'u_emqx',
      retain: 0,
    },
    sql: 'SELECT * FROM "message.dropped" WHERE topic =~ \'t/#\'',
  },
  {
    name: { en: 'client.connected', zh: '连接完成' },
    value: 'client.connected',
    description: '',
    test_field: ['clientid', 'username', 'auth_result', 'peername'],
    ctx: {
      auth_result: 'success',
      clean_start: true,
      clientid: 'c_emqx',
      connack: 0,
      connected_at: 1557818415698,
      event: 'client.connected',
      is_bridge: false,
      keepalive: 60,
      peername: '127.0.0.1:63412',
      proto_ver: 4,
      username: 'u_emqx',
      zone: 'external',
    },
    sql: 'SELECT * FROM "client.connected"',
  },
  {
    name: { en: 'client.disconnected', zh: '连接断开' },
    value: 'client.disconnected',
    description: '',
    test_field: ['clientid', 'username', 'reason_code'],
    ctx: {
      auth_result: 'success',
      clientid: 'emqx-client-EMQ-df616a68ba79d4dec133',
      event: 'client.disconnected',
      peername: '127.0.0.1:63409',
      reason_code: 'normal',
      username: 'u_emqx',
      zone: 'external',
    },
    sql: 'SELECT * FROM "client.disconnected"',
  },
  {
    name: { en: 'client.subscribe', zh: '订阅' },
    value: 'client.subscribe',
    description: '',
    test_field: ['clientid', 'username', 'topic_filters'],
    ctx: {
      auth_result: 'success',
      clientid: 'c_emqx',
      event: 'client.subscribe',
      peername: '127.0.0.1:63412',
      topic_filters: [{ topic: 't/a', qos: 0 }, { topic: 't/b', qos: 1 }],
      topic: 't/a',
      qos: 0,
      username: 'u_emqx',
      zone: 'external',
    },
    sql: 'SELECT * FROM "client.subscribe" WHERE topic =~ \'t/#\'',
  },
  {
    name: { en: 'client.unsubscribe', zh: '取消订阅' },
    value: 'client.unsubscribe',
    description: '',
    test_field: ['clientid', 'username', 'topic_filters'],
    ctx: {
      auth_result: 'success',
      clientid: 'c_emqx',
      event: 'client.unsubscribe',
      peername: '127.0.0.1:63412',
      topic_filters: ['t/a', 't/b'],
      topic: 't/a',
      qos: 0,
      username: 'u_emqx',
      zone: 'external',
    },
    sql: 'SELECT * FROM "client.unsubscribe" WHERE topic =~ \'t/#\'',
  },
]
